#!/bin/bash

## Description: Runs php code sniffer in the container
## Usage: sniff
## Example: ddev sniff
## Reference: https://github.com/squizlabs/PHP_CodeSniffer/wiki
## `||true` exempts bash from returning a non-zero exit code because of phpcs errors.

phpcs web/modules/custom/drupaleasy_repositories || true
